# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  arquillian-build-jdk8:
    name: Integration - JDK 8
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      SNAPSHOT_VERSION: ${{ steps.arq-version.outputs.SNAPSHOT_VERSION }}

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      name: JDK 8 setup
      with:
        java-version: 8
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean -B install

    - name: Version save
      id: arq-version
      run: |
        VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        echo "::set-output name=SNAPSHOT_VERSION::$VERSION"
        echo "$VERSION"

    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: arquillian
        path: ~/.m2/repository/org/jboss/

    - name: List artifacts
      run: ls -R ~/.m2/repository/org/jboss

  #arquillian-build-jdk11:
   # name: Integration - JDK 11
    #runs-on: ubuntu-latest
    #timeout-minutes: 10

#    steps:
 #   - uses: actions/checkout@v3
  #  
   # - uses: actions/setup-java@v3
    #  name: JDK 11 setup
     # with:
      #  java-version: 11
       # distribution: 'temurin'
        #cache: maven
        
    #- name: Build with Maven
    #  run: mvn clean -B verify
  
  #integration-wildfly-job:
  #  runs-on: ubuntu-latest
  # name: Integration verification for WildFly
  #  needs: arquillian-build-jdk8
#
 #   steps:
  #    - uses: actions/checkout@v3
#
 #     - uses: actions/download-artifact@v3
  #      with:
   #       name: arquillian
    #      path: ~/.m2/repository/org/jboss
#
 #     - uses: actions/setup-java@v3
  #      name: JDK 11 setup
   #     with:
    #      java-version: 11
     #     distribution: 'temurin'
      #    cache: maven
#
 #     - uses: actions/checkout@v3
  #      name: Checkout WildFly
   #     with:
    #      repository: wildfly/wildfly 
#
 #     - name: WildFly integration
  #      env:
   #       SNAPSHOT_VERSION: ${{ needs.arquillian-build-jdk8.outputs.SNAPSHOT_VERSION }}
    #    run: |
     #     mvn clean install -DskipTests -DskipITs -Denforcer.skip -Dversion.org.jboss.arquillian.core="$SNAPSHOT_VERSION"
